# Generated by Django 3.2.25 on 2024-05-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
